In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5]).reshape(1,-1)
x.T + x

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [3]:
x.T.shape, x.shape

((5, 1), (1, 5))

In [4]:
v = np.array([1,2,3,4])

v.reshape(-1,1) * v

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [6]:
batch = np.array([
    [1,2,3,4],
    [1,0,1,0],
    [5,5,10,5]
])

np.array([v.reshape(-1,1) * v for v in batch])

array([[[  1,   2,   3,   4],
        [  2,   4,   6,   8],
        [  3,   6,   9,  12],
        [  4,   8,  12,  16]],

       [[  1,   0,   1,   0],
        [  0,   0,   0,   0],
        [  1,   0,   1,   0],
        [  0,   0,   0,   0]],

       [[ 25,  25,  50,  25],
        [ 25,  25,  50,  25],
        [ 50,  50, 100,  50],
        [ 25,  25,  50,  25]]])

In [21]:
batch[..., None] * v

NameError: name 'v' is not defined

In [20]:
np.array([batch[..., None] * s.T for s in batch])

array([[[[ 1,  2,  3,  4],
         [ 2,  4,  6,  8],
         [ 3,  6,  9, 12],
         [ 4,  8, 12, 16]],

        [[ 1,  2,  3,  4],
         [ 0,  0,  0,  0],
         [ 1,  2,  3,  4],
         [ 0,  0,  0,  0]],

        [[ 5, 10, 15, 20],
         [ 5, 10, 15, 20],
         [ 5, 10, 15, 20],
         [ 5, 10, 15, 20]]],


       [[[ 1,  0,  1,  0],
         [ 2,  0,  2,  0],
         [ 3,  0,  3,  0],
         [ 4,  0,  4,  0]],

        [[ 1,  0,  1,  0],
         [ 0,  0,  0,  0],
         [ 1,  0,  1,  0],
         [ 0,  0,  0,  0]],

        [[ 5,  0,  5,  0],
         [ 5,  0,  5,  0],
         [ 5,  0,  5,  0],
         [ 5,  0,  5,  0]]],


       [[[ 5,  5,  5,  5],
         [10, 10, 10, 10],
         [15, 15, 15, 15],
         [20, 20, 20, 20]],

        [[ 5,  5,  5,  5],
         [ 0,  0,  0,  0],
         [ 5,  5,  5,  5],
         [ 0,  0,  0,  0]],

        [[25, 25, 25, 25],
         [25, 25, 25, 25],
         [25, 25, 25, 25],
         [25, 25, 25, 25]]]])

In [16]:
# есть батч из n векторов длины m (n, m). получить
# матрицы произведений для каждого вектора
# 1 слой - матрица для 1 вектора 
# 2 слой - матрица для 2 вектора, итд
# размерность тензора n*m*m

# !!!!!!!!

In [ ]:
# сохранить результаты на git epam/ github